var timers=new Array;var images=new Array;var fallbacks={};var previews={};var fallbackOngoing={};var isMobile=(function(){var check=false;(function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check=true;})(navigator.userAgent||navigator.vendor||window.opera);return check;})();function changeThumb(id,url){document.getElementById(id).src=url;}
function thumb_path(vid){var index=parseInt((vid-1)/max_thumb_folders);var tmb_folder='tmb';if(index!==0){tmb_folder='tmb'+index;}
var path='https://static-clst.avgle.com/videos/'+tmb_folder;return path;}
function startRotate(elem){var image_id=$(elem).attr("id");var id_split=image_id.split('_');var video_id=id_split[1];console.log('startRotate',video_id);if(!isMobile&&!(image_id in fallbacks)){if(image_id in previews){return;}
var def_thumb=id_split[3];var poster;if($.isNumeric(def_thumb)){poster=thumb_path(video_id)+'/'+video_id+'/1.jpg';}else{poster=thumb_path(video_id)+'/'+video_id+'/'+def_thumb+'.jpg';}
var progress=$.parseHTML('<div class="progress progress-striped active" style="height: 3px;position: absolute;width: 0%;"><div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%;"></div></div>');var video=document.createElement("video");video.src=thumb_path(video_id)+'/'+video_id+'/preview.mp4';video.poster=poster;video.className="preview-video img-responsive";video.autoplay=true;video.loop=true;video.controls=false;video.style['object-fit']='initial';var canplay=false;var animEnded=false;video.addEventListener('error',function(e){if(animEnded){$(progress).fadeOut();}
canplay=true;fallbacks[image_id]=true;elem.style.display='initial';video.outerHTML='';video.style.display='none';startRotate(elem);});video.addEventListener('canplay',function(e){if(animEnded){$(progress).fadeOut();}
canplay=true;});previews[image_id]=true;previews[video]=elem;$(elem).parent().prepend(video);$(elem).parent().prepend(progress);elem.style.display='none';elem.style.height='0px';$(progress).animate({width:'100%'},800,function(){if(canplay){$(progress).fadeOut();}
animEnded=true;});return;}
if(image_id in fallbackOngoing&&fallbackOngoing[image_id]){return;}
fallbackOngoing[image_id]=true;var thumbs=id_split[2];if(typeof thumbs=="undefined"){thumbs=20;}
for(var i=1;i<=thumbs;i++){var image_url=thumb_path(video_id)+'/'+video_id+'/'+i+'.jpg';images[i]=new Image();images[i].src=image_url;}
for(var i=1;i<=thumbs;i++){timers[i]=setTimeout("changeThumb('"+image_id+"','"+thumb_path(video_id)+'/'+video_id+'/'+i+'.jpg'+"')",i*50*10);}}
function stopRotate(elem){var image_id=$(elem).attr("id");var id_split=image_id.split('_');var video_id=id_split[1];var thumbs=id_split[2];var def_thumb=id_split[3];if(typeof thumbs=="undefined"){thumbs=20;}
for(var i=1;i<=thumbs;i++){if(typeof timers[i]=="number"){clearTimeout(timers[i]);}}
if($.isNumeric(def_thumb))
$(elem).attr('src',thumb_path(video_id)+'/'+video_id+'/'+def_thumb+'.jpg');else
$(elem).attr('src',thumb_path(video_id)+'/'+video_id+'/1.jpg');fallbackOngoing[image_id]=false;}
function isScrolledIntoView(elem){var docViewTop=$(window).scrollTop();var docViewBottom=docViewTop+$(window).height();var elemTop=$(elem).offset().top;var elemBottom=elemTop+$(elem).height();return((elemBottom<=docViewBottom)&&(elemTop>=docViewTop));}
$(document).ready(function(){$("body").on('mouseover',"img[id*='rotate_']",function(event){startRotate(this);}).on('mouseout',"img[id*='rotate_']",function(event){stopRotate(this);}).on('mouseout',".preview-video",function(event){stopRotate(previews[this]);this.autoplay=false;this.load();}).on('mouseover',".preview-video",function(event){this.play();});var elems=document.querySelectorAll(":hover");for(var i in elems){if(elems[i].tagName&&elems[i].tagName.toLowerCase()==='img'&&elems[i].className.indexOf('img-responsive')!==-1){startRotate(elems[i]);break;}}
$("h1.big-title-truncate > a[data-toggle=popover]").popover();});