document.writeln("<script async type=\"application/javascript\" src=\"https://a.888100.xyz/ad-provider.js\"></script> ");
document.writeln("<div class=\"pcbdmap\" style=\"text-align: center;\">");
document.writeln("<ins class=\"adsbyexoclick\" data-zoneid=\"4862496\"></ins> ");
document.writeln("<ins class=\"adsbyexoclick\" data-zoneid=\"4862498\"></ins>");
document.writeln("</div>");
document.writeln("<div class=\"sjbdmap\" style=\"text-align: center;\">");
document.writeln("<ins class=\"adsbyexoclick\" data-zoneid=\"4862502\"></ins> ");
document.writeln("<ins class=\"adsbyexoclick\" data-zoneid=\"4862504\"></ins>");
document.writeln("</div>");
document.writeln(" <script>(AdProvider = window.AdProvider || []).push({\"serve\": {}});</script>");